FROM python:3.11-bullseye

RUN apt update -y
RUN apt install wget\
    git \
    iproute2 \
    #bash \
    #bash-doc  \
    #bash-completion \
#    openssl-dev [\
    #golang \
#    build-base \
    build-essential \
    ca-certificates -y && update-ca-certificates

RUN curl -sSL https://install.python-poetry.org | python3 -
RUN echo export PATH="/root/.local/bin:$PATH" >> ~/.bashrc

RUN python3 -m pip install --user pipx
RUN python3 -m pipx ensurepath

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]